version: '3.8'

services:
  billingapp:
    build: ./
    command: ./wait-for-postgres.sh db ./billingapp
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_PASSWORD=v&487fnd4jbvf8

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=v&487fnd4jbvf8
    ports:
      - 5436:5432

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/data





